[package]
name = "chie"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
serde = { version = "1.0.228", features = ["derive"] }
sqlx = "0.8.6"
tokio = { version = "1.48.0", features = ["full"] }
validator = "0.20.0"
